services:
  app:
    build: .
    ports:
      - "5009:5000"
    environment:
      DB_URL: ${NEON_DB_URL}  # postgresql://user:pass@host.neon.tech/db?sslmode=require
      MODEL_PIPELINE_PATH: /app/models/healthcare_model_pipeline.pkl
      MODEL_PACKAGE_PATH: /app/models/healthcare_model.pkl
      RAW_PATH: /app/scripts/data/raw/healthcare_dataset.csv
      CLEANED_PATH: /app/scripts/data/cleaned_healthcare.csv
      KAGGLE_KEY: ${KAGGLE_KEY:-}
      FLASK_DEBUG: "false"
    entrypoint: ["/app/scripts/entrypoint.sh"]
    restart: always
    networks:
      - dokploy-network

  airflow:
    build: .
    ports:
      - "8089:8080"
    environment:
      AIRFLOW_HOME: /app/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${NEON_DB_URL_AIRFLOW:-${NEON_DB_URL}}  # can be same or separate Neon DB
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /app
      MODEL_PIPELINE_PATH: /app/models/healthcare_model_pipeline.pkl
      MODEL_PACKAGE_PATH: /app/models/healthcare_model.pkl
      RAW_PATH: /app/scripts/data/raw/healthcare_dataset.csv
      CLEANED_PATH: /app/scripts/data/cleaned_healthcare.csv
      KAGGLE_KEY: ${KAGGLE_KEY:-}
    command: >
      bash -c "
        echo 'Waiting for Neon DB...' &&
        sleep 5 &&
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
        exec airflow standalone
      "
    restart: always
    networks: 
       - dokploy-network

networks:
  dokploy-network:
    external: true